#pragma once

#include"BaseLib/Policy/CommonDefines.h"
#include"BaseLib/Policy/MaxLimit.h"
#include"BaseLib/Policy/MinLimit.h"
#include"BaseLib/Policy/Range.h"
#include"BaseLib/Policy/DestinationOrder.h"
#include"BaseLib/Policy/Durability.h"
#include"BaseLib/Policy/Liveliness.h"
#include"BaseLib/Policy/LatencyBudget.h"
#include"BaseLib/Policy/Ownership.h"
#include"BaseLib/Policy/Interval.h"
#include"BaseLib/Policy/Attempt.h"
#include"BaseLib/Policy/LoadBalance.h"
#include"BaseLib/Policy/Timeout.h"
#include"BaseLib/Policy/UndoRedo.h"
#include"BaseLib/Policy/ResourceLimits.h"
#include"BaseLib/Policy/SizeLimits.h"
#include"BaseLib/Policy/Composition.h"
#include"BaseLib/Policy/Computation.h"
#include"BaseLib/Policy/Ordering.h"
#include"BaseLib/Policy/Invocation.h"
#include"BaseLib/Policy/Priority.h"
#include"BaseLib/Policy/Reload.h"
#include"BaseLib/Policy/Criterion.h"
#include"BaseLib/Policy/Reaction.h"
#include"BaseLib/Policy/Lifespan.h"
#include"BaseLib/Policy/LeasePlan.h"
#include"BaseLib/Policy/History.h"
#include"BaseLib/Policy/TimeBasedFilter.h"
#include"BaseLib/Policy/Deadline.h"
#include"BaseLib/Policy/Throughput.h"
#include"BaseLib/Policy/Congestion.h"
#include"BaseLib/Policy/Replay.h"
#include"BaseLib/Policy/Communication.h"
#include"BaseLib/Policy/Reliability.h"
#include"BaseLib/Policy/UserData.h"
#include "Activation.h"
