#pragma once

#include"BaseLib/Templates/Value.h"
#include"BaseLib/Templates/ProtectedBool.h"
#include"BaseLib/Templates/UtilityFunctions.h"
#include"BaseLib/Templates/BaseTypes.h"
#include"BaseLib/Templates/DoubleCheckedLocking.h"
#include"BaseLib/Templates/FlyweightTypes.h"
#include"BaseLib/Templates/Synchronization.h"
#include"BaseLib/Templates/FactoryTypes.h"
#include"BaseLib/Templates/MethodInterfaces.h"
#include"BaseLib/Templates/CountingHandle.h"
#include"BaseLib/Templates/LeasingType.h"
#include"BaseLib/Templates/AnyType.h"
#include"BaseLib/Templates/AnyKeyType.h"
#include"BaseLib/Templates/KeyType.h"
#include"BaseLib/Templates/ContextObject.h"
#include"BaseLib/Templates/ContextObjectPtr.h"
#include"BaseLib/Templates/IteratorBase.h"
#include"BaseLib/Templates/Serialize.h"
#include"BaseLib/Templates/EventType.h"
#include"BaseLib/Templates/EventData.h"
#include"BaseLib/Templates/Lifecycle.h"
#include"BaseLib/Templates/TriggerCondition.h"

#include"BaseLib/Templates/StrategyMethods.h"
#include"BaseLib/Templates/FilterMethods.h"
#include"BaseLib/Templates/ActionHolder.h"
#include"BaseLib/Templates/FunctorHolder.h"
#include"BaseLib/Templates/FunctionPointer.h"
#include"BaseLib/Templates/FunctionProxy.h"
#include"BaseLib/Templates/FutureRunnable.h"
#include"BaseLib/Templates/ScheduledFuture.h"
#include"BaseLib/Templates/StrategyActionMethods.h"
#include"BaseLib/Templates/StrategyContextActionMethods.h"
#include"BaseLib/Templates/SchedulerMethods.h"
#include"BaseLib/Templates/StateMethods.h"
#include"BaseLib/Templates/NameDescription.h"
#include"BaseLib/Templates/TranslatorValidatorMethods.h"
#include"BaseLib/Templates/ObjectsManager.h"

